---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: "https://host.docker.internal:9443/mutate-friendly-orchestrate-cloud-sap-v1alpha1-greeter"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lVWk5TbHFPRFZpSzhzUXc0cDk5V21odWh5N0dnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VhRzl6ZEM1a2IyTnJaWEl1YVc1MFpYSnVZV3d3SGhjTk1qVXdNekkwTURneQpPRFEzV2hjTk1qWXdNekkwTURneU9EUTNXakFmTVIwd0d3WURWUVFEREJSb2IzTjBMbVJ2WTJ0bGNpNXBiblJsCmNtNWhiRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPTEsyZlg4c1VZaG9HT08KS0MzU1FCZGNsRnVTemtHLzVQUzJOMjVST0pBWjErbWVLRVZDWUtkcW9jV0szeWRYeWNVaU1jUTU4VzQwUFNoNQpJS2Yvb1JtQkhyMFZsMkl4bHROcUtJMlpDaFkzY2JZVkNLSGtaZGJoSURPUCtVbUxaaXNPOTVFQVlzUnBTdHQrClRTMTRsYW10ZU5ad2xDU1RWL21MbndyWDZ6NDBjeFZORDQ0WGM4U3l1OTZHZG9nZm9DZXhodFRjZzVSVURieFIKZXN3OEVDQjV6L0QzaTNKVVZMdG1VVHZZSVFqd3pEaWR6TWpicWE2SFZwenJqRGoreDZ1SWRCRXJlQmdUcjErdgo1bVZyaHVLRnhNMWxRdVR1U2lCTHRDTjllazl1Q0o5KzFHbjVjSTRkVGw1Q0twYkRrU3VDTjBocUcwenpHOTgzCnFTNUc2amNDQXdFQUFhTkNNRUF3SHdZRFZSMFJCQmd3Rm9JVWFHOXpkQzVrYjJOclpYSXVhVzUwWlhKdVlXd3cKSFFZRFZSME9CQllFRkxuc1QvU21Rdi9SQXh6MjJMNzBOYlozaFhETU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUNOMmZSSW51NGFxcDlLNjZ5aVVhNlhnWVI4TEt5Mit2VkRMNnNhcXlZeU9JWWV5ZCt0TmZObzhSZGI2RWtkCmhVeWY3ZFV4eTIyd2l0TXQ0WmtXZ0VHYVNOZ21zTDdUZnliOGNza09kbG5iRWF3UmpDSGZ1K0xQL2JBKy9KSGwKbVJrT2c5aUZJQ1hCQ1puSEx4OWF4RDIwQUh4dzNrK09DSnZEd1BkMGcxNGtEZzlYbWh2dVZmbnd0ajhGMTZsegpWODRXSUU2eWdSb3ZIZWx4NU9yS2x6TkI0VWdVY0VYN2tPZndOSVNiVThJQUw4UzFQbUFEaml5RmFkbTVFWFppClVacDFkblJVWFpRNlV1RUhINXlxVXl4c3pmMGhrRzZkUDdZOGxwLyt2SFh5ZC9uZmZhR0x1emZPbDVBVTZPdnMKZ1NGQ1k3OUpiVkFJMjlrTFpQQkF1MDBHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  failurePolicy: Fail
  name: mgreeter-v1alpha1.kb.io
  rules:
  - apiGroups:
    - friendly.orchestrate.cloud.sap
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greeters
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    url: "https://host.docker.internal:9443/validate-friendly-orchestrate-cloud-sap-v1alpha1-greeter"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREakNDQWZhZ0F3SUJBZ0lVWk5TbHFPRFZpSzhzUXc0cDk5V21odWh5N0dnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0h6RWRNQnNHQTFVRUF3d1VhRzl6ZEM1a2IyTnJaWEl1YVc1MFpYSnVZV3d3SGhjTk1qVXdNekkwTURneQpPRFEzV2hjTk1qWXdNekkwTURneU9EUTNXakFmTVIwd0d3WURWUVFEREJSb2IzTjBMbVJ2WTJ0bGNpNXBiblJsCmNtNWhiRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFPTEsyZlg4c1VZaG9HT08KS0MzU1FCZGNsRnVTemtHLzVQUzJOMjVST0pBWjErbWVLRVZDWUtkcW9jV0szeWRYeWNVaU1jUTU4VzQwUFNoNQpJS2Yvb1JtQkhyMFZsMkl4bHROcUtJMlpDaFkzY2JZVkNLSGtaZGJoSURPUCtVbUxaaXNPOTVFQVlzUnBTdHQrClRTMTRsYW10ZU5ad2xDU1RWL21MbndyWDZ6NDBjeFZORDQ0WGM4U3l1OTZHZG9nZm9DZXhodFRjZzVSVURieFIKZXN3OEVDQjV6L0QzaTNKVVZMdG1VVHZZSVFqd3pEaWR6TWpicWE2SFZwenJqRGoreDZ1SWRCRXJlQmdUcjErdgo1bVZyaHVLRnhNMWxRdVR1U2lCTHRDTjllazl1Q0o5KzFHbjVjSTRkVGw1Q0twYkRrU3VDTjBocUcwenpHOTgzCnFTNUc2amNDQXdFQUFhTkNNRUF3SHdZRFZSMFJCQmd3Rm9JVWFHOXpkQzVrYjJOclpYSXVhVzUwWlhKdVlXd3cKSFFZRFZSME9CQllFRkxuc1QvU21Rdi9SQXh6MjJMNzBOYlozaFhETU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQgpBUUNOMmZSSW51NGFxcDlLNjZ5aVVhNlhnWVI4TEt5Mit2VkRMNnNhcXlZeU9JWWV5ZCt0TmZObzhSZGI2RWtkCmhVeWY3ZFV4eTIyd2l0TXQ0WmtXZ0VHYVNOZ21zTDdUZnliOGNza09kbG5iRWF3UmpDSGZ1K0xQL2JBKy9KSGwKbVJrT2c5aUZJQ1hCQ1puSEx4OWF4RDIwQUh4dzNrK09DSnZEd1BkMGcxNGtEZzlYbWh2dVZmbnd0ajhGMTZsegpWODRXSUU2eWdSb3ZIZWx4NU9yS2x6TkI0VWdVY0VYN2tPZndOSVNiVThJQUw4UzFQbUFEaml5RmFkbTVFWFppClVacDFkblJVWFpRNlV1RUhINXlxVXl4c3pmMGhrRzZkUDdZOGxwLyt2SFh5ZC9uZmZhR0x1emZPbDVBVTZPdnMKZ1NGQ1k3OUpiVkFJMjlrTFpQQkF1MDBHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  failurePolicy: Fail
  name: vgreeter-v1alpha1.kb.io
  rules:
  - apiGroups:
    - friendly.orchestrate.cloud.sap
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - greeters
  sideEffects: None