# This rule is not used by the project k8s-webhook-learning itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over friendly.orchestrate.cloud.sap.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-webhook-learning
    app.kubernetes.io/managed-by: kustomize
  name: greeter-admin-role
rules:
- apiGroups:
  - friendly.orchestrate.cloud.sap
  resources:
  - greeters
  verbs:
  - '*'
- apiGroups:
  - friendly.orchestrate.cloud.sap
  resources:
  - greeters/status
  verbs:
  - get
