# This rule is not used by the project k8s-webhook-learning itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to friendly.orchestrate.cloud.sap resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-webhook-learning
    app.kubernetes.io/managed-by: kustomize
  name: greeter-viewer-role
rules:
- apiGroups:
  - friendly.orchestrate.cloud.sap
  resources:
  - greeters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - friendly.orchestrate.cloud.sap
  resources:
  - greeters/status
  verbs:
  - get
