apiVersion: friendly.orchestrate.cloud.sap/v1alpha1
kind: Greeter
metadata:
  labels:
    app.kubernetes.io/name: k8s-webhook-learning
    app.kubernetes.io/managed-by: kustomize
  name: greeter-sample
spec:
  # TODO(user): Add fields here
